name: purrfact
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.4+8

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: 5.4.0
  flutter_native_splash: 2.3.8
  get_it: 7.6.4
  logger: 2.0.2+1
  watch_it: 1.1.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'dart run flutter_launcher_icons:main'
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: 'assets/icon.png'
    background_color: '#27786F'
    theme_color: '#27786F'
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#27786F'
  adaptive_icon_foreground: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'dart run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  web: true
  color: '#27786F'
  color_web: '#27786F'
  image: 'assets/icon.png'
  image_web: 'assets/icon.png'
  web_image_mode: center

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Product Sans
      fonts:
        - asset: fonts/Product Sans Bold.ttf
